### PR TITLE
chore: Add tests for CCC stateIntoSpec

### PR DESCRIPTION
**Pull request by acpana**
Rebases #1366 and integrates by adding a small change to use DeleteResources without waiting.

### CODE REVIEW

**Comment by justinsb** [comment]
Thanks @acpana 

/approve
/lgtm

I think you need to fix the merge conflict though!

**Comment by acpana** [comment]
@justinsb merge conflicts should be resolved now.  🙏🏼  I'm still not sure if this helps or causes more confusion with #1368.

If it's ok w you and @maqiuyujoyce I'm willing to take on and address any feedback that Joyce raised in 1368 in a follow up PR.

**Comment by justinsb** [comment]
Thanks @acpana 

/approve
/lgtm

**Pull request merged**
