### PR TITLE
Promote WorkstationCluster to v1beta1

### PR DESCRIPTION
**Pull request by jasonvigil**

### CODE REVIEW

**Review by yuwenma — COMMENTED** [review]
Promotion code looks good. Could you add the sample code and reference doc as well?
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/docs/develop-resources/deep-dives/5-releases.md#52-bump-from-v1alpha1-to-v1beta1

**Comment by jasonvigil** [comment]
> Promotion code looks good. Could you add the sample code and reference doc as well? https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/docs/develop-resources/deep-dives/5-releases.md#52-bump-from-v1alpha1-to-v1beta1

@yuwenma I believe this is done already? Maybe need to refresh

**Pull request merged**
