### PR TITLE
chore: upgrade dcl to v1.61

### PR DESCRIPTION
**Pull request by acpana**
Upgrade to DCL v1.61 (release notes: https://github.com/GoogleCloudPlatform/declarative-resource-client-library/releases/tag/v1.61.0)

Instructions as per https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/README.UpdatingDCL.md where I pinned the v1.61 version.

### CODE REVIEW

**Comment by acpana** [comment]
/hold

my first time upgrading this lib

**Comment by maqiuyujoyce** [comment]
As integration tests are not triggered as part of the presubmit, if it is not expensive, could you run the dynamic test and samples test locally for GKEHubFeatureMembership resources to verify the changes won't cause issues?
The postsubmit test jobs don't cover this resource, so an alternative is we wait after rebase to test it out in the release test jobs.

**Comment by acpana** [comment]
@maqiuyujoyce thanks for the guidance. Here's the local runs:

```
# samples
$ go test -v -tags=integration ./config/tests/samples/create -timeout 1600s -test.count=1 -test.run TestAll -run-tests gkehub 2>&1
...
--- PASS: TestAll (1.10s)
    --- PASS: TestAll/gkehubmembership (601.25s)
PASS
...
ok      github.com/GoogleCloudPlatform/k8s-config-connector/config/tests/samples/create 671.571s

# dynamic
$ go test -v -tags=integration ./pkg/controller/dynamic/ -timeout 1600s -test.count=1 -test.run TestCreateNoChangeUpdateDelete -run-tests gkehub 2>&1
...
--- PASS: TestCreateNoChangeUpdateDelete (0.08s)
    --- PASS: TestCreateNoChangeUpdateDelete/gkehub (0.00s)
        --- PASS: TestCreateNoChangeUpdateDelete/gkehub/basic-gkehubmembership (769.32s)
PASS
...
ok      github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/dynamic      779.041s
```

/hold cancel

**Pull request merged**
