### PR TITLE
Turn on gkehubfeaturemembership direct controller

### PR DESCRIPTION
**Pull request by ziyue-101**
### Change description

Use gkehub direct controller.
I verified that post submit tests are passing for gkehubfeaturemembership resource.

### Tests you have done

- [ ] Run `make ready-pr` to ensure this PR is ready for review.
- [ ] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by ziyue-101** [comment]
/hold

Need to verify the postsubmit test passes

**Comment by justinsb** [comment]
/lgtm

Will leave approval to @yuwenma

**Comment by yuwenma** [comment]
/hold

I think we want to gather more clear signals in the golden log to validate this PR before turning it on.  Can you refer to [this guide](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/docs/develop-resources/scenarios/migrate-tf-resource-beta.md#add-mockgcp-tests) to make sure this resource has everything we need.

**Comment by acpana** [comment]
Thanks @ziyue-101 for this!

One small cleanup item for us would be to remove the `GKEHubFeatureMembership` from controls like the `KCC_USE_DIRECT_RECONILER`s but that can happen after this.

/lgtm
/approve

cc @yuwenma / @maqiuyujoyce could one of you +1? Happy to answer any questions you'd have.

**Pull request merged**
