### PR TITLE
tests: Fix container clusters fixtures test data

### PR DESCRIPTION
**Pull request by gemmahou**
### Change description

The container clusters e2e test failed because of an error in the test data.
It's concerning that our dynamic test doesn't catch that.

### Tests you have done

- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [x] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by justinsb** [comment]
Good catch & thanks for fixing!

Are we tracking "It's concerning that our dynamic test doesn't catch that." anywhere?  I agree it's very concerning.  Does our unified test catch it?

**Comment by gemmahou** [comment]
> Good catch & thanks for fixing!
> 
> Are we tracking "It's concerning that our dynamic test doesn't catch that." anywhere? I agree it's very concerning. Does our unified test catch it?

Yes, our unified test failed. 
We have an open issue for this I believe: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/1201

**Comment by maqiuyujoyce** [comment]
Good to know that the unified test caught it! In dynamic test and samples test, we wanted to leverage the webhook to validate the unknown field but it doesn't work properly: b/193745253.

**Comment by maqiuyujoyce** [comment]
/lgtm
/approve

/hold
@justinsb do you have other feedback about this change?

**Comment by gemmahou** [comment]
This has been fixed in another PR.

**Pull request closed without merging**
