### PR TITLE
Revert "MockGCP: Support for ComputeServiceAttachment"

### PR DESCRIPTION
**Pull request by gemmahou**
Reverts GoogleCloudPlatform/k8s-config-connector#2583

### CODE REVIEW

**Comment by justinsb** [comment]
Why do we want to revert?  Can you link a GitHub issue or similar?

**Comment by gemmahou** [comment]
> Why do we want to revert? Can you link a GitHub issue or similar?

The presubmit samples failed after this commit: https://screenshot.googleplex.com/8cgjE9ChvekNQVp.png, job: https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/10681623224/job/29605684721, and that blocks the open PRs.

The two failed tests are samples/regional-forwarding-rule-vpc-psc and samples/computeserviceattachment(flaky).

Checking the logs, the forwarding rule is a dependency of the service attachment, and the deletion of the forwarding rule is blocked because there is no network (the network was deleted before). It seems like we need to handle the deletion ordering in the direct controller. It's strange that the presubmit on the original PR passed. I had a temporary fix: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2614, but the two tests are still failing, so I think there's a deeper issue (deletion ordering, etc.).

**Comment by justinsb** [comment]
Maybe we can just revert the ComputeForwardingRule support in `func MaybeSkip` instead of a full revert?

**Comment by justinsb** [comment]
And on the deeper fix, it sounds like you're saying that the old controller was able to tolerate the network not existing, and the new controller is not.  I think this is because we resolve all dependencies in AdapterForObject.  Maybe in practice we don't want to do that for a Delete.  Either we have a dedicated method/path (e.g. `AdapterForObjectDeletion`) or we pass a parameter like `delete bool` to `AdapterForObject`, as we know in this case we don't need to do any resolution other than for the "primary key" (selfLink) of the object.

**Pull request closed without merging**
