### PR TITLE
chore: remove crds staging dir

### PR DESCRIPTION
**Pull request by acpana**
This may have happened as a result of a bad merge.  Clean up and run `make manifests`.

### CODE REVIEW

**Comment by gemmahou** [comment]
Looks good to me, could you also run `make ready-pr` or `make manifests` to regenerate the deepcopy file?

**Comment by justinsb** [comment]
LGTM on deleting the config directory

I'm not sure I understand what's going on with deepcopy

**Comment by gemmahou** [comment]
Can we rebase this master, re-run `make manifests` locally(that will re-generate the zz_generated_deepcopy, the two zz_generated_deepcopy diff files will be removed from this PR), and get the presubmit passed.

**Comment by gemmahou** [comment]
/lgtm
/approve

Thanks!! 💯

**Pull request merged**
