### PR TITLE
tests: small changes for dataformrespository

### PR DESCRIPTION
**Pull request by acpana**
Some small changes to the DataformRepository tests and implementation for Export.

### CODE REVIEW

**Comment by anhdle-sso** [comment]
you might need to add the resource to https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/pkg/test/resourcefixture/sets.go#L89

**Comment by acpana** [comment]
Also renamed to `basic` now that https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2896 is in

**Pull request merged**
