### PR TITLE
Fix "certificate" typo in description

### PR DESCRIPTION
**Pull request by justinsb**
This makes it into the docs.

### CODE REVIEW

**Comment by justinsb** [comment]
(I do expect this will fail because I need to generate docs / crds etc.  I want to verify that is the case)

**Comment by jingyih** [comment]
Test failure says `make generate-go-client` is needed. Did you use `make ready-pr` to generate the files for the second commit?

**Comment by justinsb** [comment]
> Did you use make ready-pr to generate the files for the second commit?

Not yet, but running it now :-)  I'm sort of going through the contributor experience here.  Obviously it would be better if we didn't require contributors to generate code, but as long as the tests catch it that is okay IMO.

**Pull request merged**
