### PR TITLE
mockgcp: support VertexAIEndpoint

### PR DESCRIPTION
**Pull request by jingyih**
### Change description

Fixes b/329281490

### Tests you have done

- [ ] Run `make ready-pr` to ensure this PR is ready for review.
- [x] Perform necessary E2E testing for changed resources.

```
$ E2E_KUBE_TARGET=envtest RUN_E2E=1 E2E_GCP_TARGET=mock go test -test.count=1 -timeout 600s -v ./tests/e2e -run TestAllInSeries/fixtures/vertexaiendpoint  2>&1 | tee log
```

### CODE REVIEW

**Comment by jingyih** [comment]
PR rebased.

**Comment by justinsb** [comment]
Thanks - I _think_ this includes #1324 so I looked only at the mockgcp changes here - they look good.  I assume we want to merge #1324 first (but it's great to see the mock also!)

**Comment by jingyih** [comment]
> Thanks - I _think_ this includes #1324 so I looked only at the mockgcp changes here - they look good. I assume we want to merge #1324 first (but it's great to see the mock also!)

Yeah. I will rebase this PR once #1324 is merged.

**Comment by jingyih** [comment]
Closing in favor of #1665

**Pull request closed without merging**
