### PR TITLE
test: test NoChange after Update in dynamic test

### PR DESCRIPTION
**Pull request by jingyih**
Make a no-change update after the update test. Ensure there is no unexpected update call.

This test could help catch bugs like #1802.

Without the fix in #1803, the test fails with
```
go test -timeout 1200s -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests mysqlinstance
...
k8s.go:84: expected event with reason 'Updating' to not be recorded for SQLInstance epqxuxkxxi5dnnbghdaq/sqlinstance-sample-epqxuxkxxi5dnnbghdaq, but it was
...
--- FAIL: TestCreateNoChangeUpdateDelete (0.16s)
    --- FAIL: TestCreateNoChangeUpdateDelete/sql (0.00s)
        --- FAIL: TestCreateNoChangeUpdateDelete/sql/basic-mysqlinstance (337.22s)
...
```

With the fix in #1803, the test passes
```
go test -timeout 1200s -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests mysqlinstance
...
--- PASS: TestCreateNoChangeUpdateDelete (0.16s)
    --- PASS: TestCreateNoChangeUpdateDelete/sql (0.00s)
        --- PASS: TestCreateNoChangeUpdateDelete/sql/basic-mysqlinstance (395.45s)
```

### CODE REVIEW

**Comment by maqiuyujoyce** [comment]
@jingyih some thoughts regarding this change:

I agree that adding a nochange step after the update will help identify #1802 sooner, though I feel it might be an one-off case that simply adding one step won't help at scale.

The root cause of the issue seems to be that after updating the value from `""` to `"ENTERPRISE"`, the returned value is still `""` from the GCP API - basically it is a bug from the API.
If we want to identify such an issue (rare and hard to identify; related to field defaulting and update) at scale, it means that in tests:
1. We need to have field coverage for any new field.
2. We need to at least have value coverage of the variants of the default value for any field. We probably also need to cover all the possible values for any enum field.
3. We need to have use-case coverage for transitions among the values for the any field, i.e. updating any field multiple times to different values, and always having a nochange step after an update.
 
What this PR covers is part of step 3 above, which probably will help achieving our eventual goal of test coverage, but I'm concerned that additional time will be added to the integration test suite that causes timeout in the test job. Have you got the chance to verify that?

Also, how often have we run into similar issues so far? (This is the first one afaik.) If adding this steps makes the test take longer to run, I'm not convinced we should support it for all the test cases at the moment unless it is a common issue.

**Comment by jingyih** [comment]
@maqiuyujoyce Thank you for sharing your thoughts!

> What this PR covers is part of step 3 above, which probably will help achieving our eventual goal of test coverage, but I'm concerned that additional time will be added to the integration test suite that causes timeout in the test job. Have you got the chance to verify that?

My thinking was that adding one more verification (after the update test) could improve the test coverage in general. But I agree this is a tradeoff between: 1. how much improvement in test coverage this PR brings, and 2. how much additional time it requires. For 1, we can argue that we already have similar verification after the create test. So the test coverage improvement by this PR is only for special cases such as the "edition" field of `SQLInstance`. For 2, I could copy this PR to Gerrit and find out.

The original ask is that we want to add test coverage for #1802. Maybe I was looking at the wrong direction. Do you see an simpler way to test #1802?

**Comment by jingyih** [comment]
Based on two test runs, adding additional test step in this PR is increasing the test run time from "48m53s" to "1h3m11s".

Alternatively, we could ONLY "opt-in" SQL instance for the additional test step. We would likely need a new flag `resourceContext.TestNoChangeAfterUpdate`. WDYT? @maqiuyujoyce

**Comment by maqiuyujoyce** [comment]
> Based on two test runs, adding additional test step in this PR is increasing the test run time from "48m53s" to "1h3m11s".

I think what I'm concerned about is a different job. Will discuss offline about it.

> Alternatively, we could ONLY "opt-in" SQL instance for the additional test step. We would likely need a new flag resourceContext.TestNoChangeAfterUpdate. WDYT? @maqiuyujoyce

This works for me; I'm also okay with a local allowlist for it.

**Comment by jingyih** [comment]
Added a local allowlist. The "NoChangeAfterUpdate" test is only enabled for `SQLInstance` resource.

**Review by yuwenma — COMMENTED** [review]
/lgtm
/approve

I was originally thinking of adding MockGCP test with custom steps.  This looks good.

**Comment by yuwenma** [comment]
Sorry I just checked the code and didn't notice your previous discussions @maqiuyujoyce @jingyih.

The testing I originally thought of is using MockGCP that you can mimic how the SQL server UPDATE behaves, and make it as likely as possible to the real SQL server.
Here's [an example](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/mockgcp/mockspanner/admin/instance.go#L81), the SQL server has an unpleasant behavior about its CREATE and UPDATE: `nodeCount` and `processingUnit`  is correlated (1 nodecount = 1000 processing unit), but only one value can be given on CREATE and UPDATE only accept number increasing.

**Pull request merged**
