### PR TITLE
Remove usage of binauthz in samples as it is no longer supported

### PR DESCRIPTION
**Pull request by diviner524**
### Change description

Remove binauthz from sample as it is no longer support.
Fixes b/307983504

### Tests you have done

This sample test is currently disabled.

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/f8961f9694dda6124095cbc2addad4e201790aea/config/tests/samples/create/samples_test.go#L171

- [X] Run `make ready-pr` to ensure this PR is ready for review.
- [N/A] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Review by jingyih — COMMENTED** [review]
Should this line be removed as well?
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/f8961f9694dda6124095cbc2addad4e201790aea/pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/update.yaml#L44

**Comment by diviner524** [comment]
> Should this line be removed as well?
> 
> https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/f8961f9694dda6124095cbc2addad4e201790aea/pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/update.yaml#L44

Good point, updated so we don't include this feature at all in our test data.

**Comment by diviner524** [comment]
> As @jingyih suggested, I guess we might also want to remove this object (actually, is the `binauthz` object field completely removed, or just the nested field?) from create.yaml?
> 
> Also I recall we changed the process to deal with the cloud code snippets generation, so should that be updated too?

I mentioned this to Haiyan, hope she can help to clarify in this PR.

**Review by maqiuyujoyce — APPROVED** [review]
LGTM. If any new change is needed, we can always create new PRs.

**Comment by haiyanmeng** [comment]
> > As Jingyi Hu suggested, I guess we might also want to remove this object (actually, is the `binauthz` object field completely removed, or just the nested field?) from create.yaml?
> > Also I recall we changed the process to deal with the cloud code snippets generation, so should that be updated too?
> 
> I mentioned this to Haiyan, hope she can help to clarify in this PR.

@diviner524 , I never made any change to https://github.com/GoogleCloudPlatform/k8s-config-connector. Are these samples auto-generated?

**Comment by diviner524** [comment]
> > > As Jingyi Hu suggested, I guess we might also want to remove this object (actually, is the `binauthz` object field completely removed, or just the nested field?) from create.yaml?
> > > Also I recall we changed the process to deal with the cloud code snippets generation, so should that be updated too?
> > 
> > 
> > I mentioned this to Haiyan, hope she can help to clarify in this PR.
> 
> @diviner524 , I never made any change to https://github.com/GoogleCloudPlatform/k8s-config-connector. Are these samples auto-generated?

@haiyanmeng Sorry for the confusion. The question is "is the binauthz object field completely removed, or just the nested field". In other words shall we remove the whole `binauthz` field or some nested field under it.

**Comment by haiyanmeng** [comment]
> > > > As Jingyi Hu suggested, I guess we might also want to remove this object (actually, is the `binauthz` object field completely removed, or just the nested field?) from create.yaml?
> > > > Also I recall we changed the process to deal with the cloud code snippets generation, so should that be updated too?
> > > 
> > > 
> > > I mentioned this to Haiyan, hope she can help to clarify in this PR.
> > 
> > 
> > Shuxian , I never made any change to https://github.com/GoogleCloudPlatform/k8s-config-connector. Are these samples auto-generated?
> 
> @haiyanmeng Sorry for the confusion. The question is "is the binauthz object field completely removed, or just the nested field". In other words shall we remove the whole `binauthz` field or some nested field under it.

The GKE Hub CLH rejects any feature membership including the `binauthz` field. So we should remove the whole `binauthz` field from config-connector.

**Comment by diviner524** [comment]
> > > > > As Jingyi Hu suggested, I guess we might also want to remove this object (actually, is the `binauthz` object field completely removed, or just the nested field?) from create.yaml?
> > > > > Also I recall we changed the process to deal with the cloud code snippets generation, so should that be updated too?
> > > > 
> > > > 
> > > > I mentioned this to Haiyan, hope she can help to clarify in this PR.
> > > 
> > > 
> > > Shuxian , I never made any change to https://github.com/GoogleCloudPlatform/k8s-config-connector. Are these samples auto-generated?
> > 
> > 
> > @haiyanmeng Sorry for the confusion. The question is "is the binauthz object field completely removed, or just the nested field". In other words shall we remove the whole `binauthz` field or some nested field under it.
> 
> The GKE Hub CLH rejects any feature membership including the `binauthz` field. So we should remove the whole `binauthz` field from config-connector.

Sounds good, thank you for confirming! Then we are making the right update here.

**Pull request merged**
