### PR TITLE
fixing linter errors

### PR DESCRIPTION
**Pull request by barney-s**
### Change description

Addressing Linter errors

### CODE REVIEW

**Comment by barney-s** [comment]
Linter Errors seen: 
```
Running [/home/runner/golangci-lint-1.59.1-linux-amd64/golangci-lint run --path-prefix=./experiments/compositions/composition] in [/home/runner/work/k8s-config-connector/k8s-config-connector/experiments/compositions/composition] ...
  Received 1071723 of 1071723 (100.0%), 1.0 MBs/sec
  Error: experiments/compositions/composition/tests/utils/utils.go:74:14: Error return value of `mgr.Start` is not checked (errcheck)
  	go mgr.Start(ctrl.SetupSignalHandler())
  	            ^
  Error: experiments/compositions/composition/tests/cluster/kind/cluster.go:105:17: Error return value of `os.Remove` is not checked (errcheck)
  	defer os.Remove(clusterConfig)
  	               ^
  Error: experiments/compositions/composition/tests/cluster/kind/cluster.go:303:31: Error return value of `clusterConfigFile.Close` is not checked (errcheck)
  	defer clusterConfigFile.Close()
  	                             ^
  Error: experiments/compositions/composition/tests/cluster/kind/cluster.go:324:17: Error return value of `os.Remove` is not checked (errcheck)
  	defer os.Remove(kubeConfigFile.Name())
  	               ^
  Error: experiments/compositions/composition/tests/cluster/kind/cluster.go:331:22: Error return value of `kubeConfigFile.Close` is not checked (errcheck)
  	kubeConfigFile.Close()
  	                    ^
  Error: experiments/compositions/composition/tests/cluster/kind/cluster.go:349:18: Error return value of `conn.Close` is not checked (errcheck)
  	defer conn.Close()
  	                ^
  Error: experiments/compositions/composition/tests/cluster/kind/cluster.go:3[29](https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/10392363044/job/28777370178?pr=2503#step:4:31):17: unnecessary conversion (unconvert)
  	bytes := []byte(content)
  	               ^
  Error: experiments/compositions/composition/tests/cluster/kind/cluster.go:187:2: S1006: should use for {} instead of for true {} (gosimple)
  	for true {
  	^
  Error: experiments/compositions/composition/tests/cluster/kind/cluster.go:136:12: ineffectual assignment to err (ineffassign)
  		objects, err := manifest.ParseObjects(context.Background(), string(manifests))
  		         ^
  Error: experiments/compositions/composition/tests/cluster/kind/cluster.go:3[30](https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/10392363044/job/28777370178?pr=2503#step:4:32):5: ineffectual assignment to err (ineffassign)
  	_, err = kubeConfigFile.Write(bytes)
  	   ^
  Error: experiments/compositions/composition/tests/cluster/kind/cluster.go:20:2: SA1019: "io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package [io] or package [os], and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
  	"io/ioutil"
  	^
  Error: experiments/compositions/composition/tests/cluster/kind/cluster.go:205:14: SA1004: sleeping for 2 nanoseconds is probably a bug; be explicit if it isn't (staticcheck)
  		time.Sleep(2)
  		           ^
  Error: experiments/compositions/composition/api/v1alpha1/plan_types.go:63:30: `succesfully` is a misspelling of `successfully` (misspell)
  	// Facade's generation last succesfully reconciled
  	                            ^
  Error: experiments/compositions/composition/api/v1alpha1/plan_types.go:65:33: `succesfully` is a misspelling of `successfully` (misspell)
  	// Composition generation last succesfully reconciled
  	                               ^
  Error: experiments/compositions/composition/api/v1alpha1/plan_types.go:40:2: SA9004: only the first constant in this group has an explicit type (staticcheck)
  	HEALTHY   HealthType = "Healthy"
  	^
  experiments/compositions/composition/tests/cluster/configcontroller/cluster.go:177: line is 142 characters (lll)
  	//gcloud projects add-iam-policy-binding "${PROJECT_ID}" --member "serviceAccount:${SA_EMAIL}" --role "roles/owner" --project "${PROJECT_ID}"
  experiments/compositions/composition/tests/cluster/configcontroller/cluster.go:187: line is 141 characters (lll)
  	//kubectl patch k8sallowedresources.constraints.gatekeeper.sh block-workloads --patch '{"spec":{"enforcementAction":"dryrun"}}' --type merge
  experiments/compositions/composition/tests/cluster/configcontroller/cluster.go:196: line is 183 characters (lll)
  	//kubectl label validatingwebhookconfigurations.admissionregistration.k8s.io gatekeeper-validating-webhook-configuration policycontroller.configmanagement.gke.io/managed-by-operator-
  experiments/compositions/composition/tests/cluster/configcontroller/cluster.go:202: line is 177 characters (lll)
  	//kubectl patch validatingwebhookconfigurations.admissionregistration.k8s.io gatekeeper-validating-webhook-configuration --type=json -p '[ {"op":"remove","path":"/webhooks"} ]'
  experiments/compositions/composition/tests/cluster/configcontroller/cluster.go:209: line is 176 characters (lll)
  	//  kubectl patch K8sAllowedResources forbidden-namespaces --type=json --patch '[ {"op":"add","path":"/spec/parameters/exemptedNamespaces/-", "value": "composition-system"} ]'
  experiments/compositions/composition/tests/cluster/configcontroller/cluster.go:211: line is 123 characters (lll)
  	//  kubectl patch K8sAllowedResources forbidden-namespaces --patch  '{"spec":{"enforcementAction":"dryrun"}}' --type merge
  experiments/compositions/composition/tests/cluster/configcontroller/cluster.go:227: line is 147 characters (lll)
  			"https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring,https://www.googleapis.com/auth/devstorage.read_only",
  experiments/compositions/composition/tests/cluster/configcontroller/cluster.go:232: line is 174 characters (lll)
  	//export defaultGCESA="$(gcloud iam service-accounts list --format=json | jq '.[] | select(.displayName == "Compute Engine default service account") | .email' | xargs echo)"
  Error: experiments/compositions/composition/tests/cluster/configcontroller/cluster.go:3[31](https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/10392363044/job/28777370178?pr=2503#step:4:33):2: S1006: should use for {} instead of for true {} (gosimple)
  	for true {
  	^
  Error: experiments/compositions/composition/tests/cluster/configcontroller/cluster.go:251:12: ineffectual assignment to err (ineffassign)
  		objects, err := manifest.ParseObjects(context.Background(), string(manifests))
  		         ^
  Error: experiments/compositions/composition/tests/cluster/configcontroller/cluster.go:20:2: SA1019: "io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package [io] or package [os], and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
  	"io/ioutil"
  	^
  Error: experiments/compositions/composition/tests/cluster/configcontroller/cluster.go:349:14: SA1004: sleeping for 2 nanoseconds is probably a bug; be explicit if it isn't (staticcheck)
  		time.Sleep(2)
  		           ^
  Error: experiments/compositions/composition/tests/scenario/scenario.go:61:2: field `namespace` is unused (unused)
  	namespace       string
  	^
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:37: File is not `gofmt`-ed with `-s` (gofmt)
  		&unstructured.Unstructured{
  experiments/compositions/composition/tests/testcases/simple_samples_test.go:36: File is not `gofmt`-ed with `-s` (gofmt)
  		&unstructured.Unstructured{
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:57: line is 128 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "iam.cnrm.cloud.google.com", Version: "v1beta1", Kind: "IAMServiceAccount"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:59: line is 127 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "iam.cnrm.cloud.google.com", Version: "v1beta1", Kind: "IAMPartialPolicy"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:61: line is 127 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "iam.cnrm.cloud.google.com", Version: "v1beta1", Kind: "IAMPartialPolicy"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:63: line is 128 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "storage.cnrm.cloud.google.com", Version: "v1beta1", Kind: "StorageBucket"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:65: line is 134 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "core.cnrm.cloud.google.com", Version: "v1beta1", Kind: "ConfigConnectorContext"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:67: line is 130 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "resourcemanager.cnrm.cloud.google.com", Version: "v1beta1", Kind: "Project"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:125: line is 122 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "sql.cnrm.cloud.google.com", Version: "v1beta1", Kind: "SQLInstance"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:127: line is 122 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "sql.cnrm.cloud.google.com", Version: "v1beta1", Kind: "SQLInstance"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:130: line is 121 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "kms.cnrm.cloud.google.com", Version: "v1beta1", Kind: "KMSKeyRing"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:1[32](https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/10392363044/job/28777370178?pr=2503#step:4:34): line is 121 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "kms.cnrm.cloud.google.com", Version: "v1beta1", Kind: "KMSKeyRing"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:134: line is 123 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "kms.cnrm.cloud.google.com", Version: "v1beta1", Kind: "KMSCryptoKey"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:136: line is 123 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "kms.cnrm.cloud.google.com", Version: "v1beta1", Kind: "KMSCryptoKey"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:139: line is 126 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "iam.cnrm.cloud.google.com", Version: "v1beta1", Kind: "IAMPolicyMember"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:141: line is 126 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "iam.cnrm.cloud.google.com", Version: "v1beta1", Kind: "IAMPolicyMember"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:144: line is 135 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "serviceusage.cnrm.cloud.google.com", Version: "v1beta1", Kind: "ServiceIdentity"},
  experiments/compositions/composition/tests/testcases/kcc_samples_test.go:147: line is 127 characters (lll)
  		{GroupVersionKind: schema.GroupVersionKind{Group: "serviceusage.cnrm.cloud.google.com", Version: "v1beta1", Kind: "Service"},
  Error: experiments/compositions/composition/tests/testcases/main_test.go:40:2: SA1019: rand.Seed has been deprecated since Go 1.20 and an alternative has been available since Go 1.0: As of Go 1.20 there is no reason to call Seed with a random value. Programs that call Seed with a known value to get a specific sequence of results should use New(NewSource(seed)) to obtain a local random generator. (staticcheck)
  	rand.Seed(time.Now().UnixNano())
  	^
  Error: experiments/compositions/composition/expanders/jinja2/main.go:67:20: Error return value of `os.RemoveAll` is not checked (errcheck)
  	defer os.RemoveAll(dir)
  	                  ^
  Error: experiments/compositions/composition/expanders/jinja2/main.go:102:20: Error return value of `os.RemoveAll` is not checked (errcheck)
  	defer os.RemoveAll(dir)
  	                  ^
  experiments/compositions/composition/expanders/jinja2/main.go:94: line is 140 characters (lll)
  	//log.Printf("EvaluateRequest:\n  config: %s\n  context: %s\n  facade: %s\n  values: %s\n", req.Config, req.Context, req.Facade, req.Value)
  experiments/compositions/composition/expanders/jinja2/main.go:219: line is 172 characters (lll)
  	//log.Printf("Result:\n  type: %s\n  error: %s\n  status: %s\n  manifests: %s\n  values: %s\n", result.Type, result.Errors, result.Status, result.Manifests, result.Values)
  Error: experiments/compositions/composition/expanders/jinja2/main.go:173:77: (*expander).Validate - result 1 (error) is always nil (unparam)
  func (e *expander) Validate(result *pb.ValidateResult) (*pb.ValidateResult, error) {
                                                                              ^
  Error: experiments/compositions/composition/expanders/jinja2/main_test.go:73:12: string `{"key": "val"}` has 7 occurrences, make it a constant (goconst)
  	config := "{\"key\": \"val\"}"
  	          ^
  Error: experiments/compositions/composition/expanders/jinja2/main_test.go:167:25: string `has no attribute 'zone'` has 3 occurrences, make it a constant (goconst)
  	expectedErrorString := "has no attribute 'zone'"
  	                       ^
  Error: experiments/compositions/composition/expanders/jinja2/main_test.go:42:2: SA1019: rand.Seed has been deprecated since Go 1.20 and an alternative has been available since Go 1.0: As of Go 1.20 there is no reason to call Seed with a random value. Programs that call Seed with a known value to get a specific sequence of results should use New(NewSource(seed)) to obtain a local random generator. (staticcheck)
  	rand.Seed(time.Now().UnixNano())
  	^
  Error: experiments/compositions/composition/expanders/jinja2/main_test.go:45:15: SA1019: grpc.Dial is deprecated: use NewClient instead.  Will be supported throughout 1.x. (staticcheck)
  	conn, err := grpc.Dial(*addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
  	             ^
  Error: experiments/compositions/composition/pkg/applier/applier.go:179:21: Error return value of `item.SetNamespace` is not checked (errcheck)
  			item.SetNamespace(a.namespace)
  			                 ^
  experiments/compositions/composition/pkg/crds/crds.go:92: File is not `gofmt`-ed with `-s` (gofmt)
  		"conditions": apiextensions.JSONSchemaProps{
  experiments/compositions/composition/pkg/crds/crds.go:88: line is 148 characters (lll)
  	if err := apiextensionsv1.Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps(specProperties, specUnversionedProperties, nil); err != nil {
  experiments/compositions/composition/pkg/crds/crds.go:129: line is 152 characters (lll)
  							Description: "type of condition in CamelCase or in foo.example.com/CamelCase. The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)",
  experiments/compositions/composition/pkg/crds/crds.go:131: line is 135 characters (lll)
  							Pattern:     "^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$",
  experiments/compositions/composition/cmd/inline/main.go:298: line is 124 characters (lll)
  	klog.Infof("group: %s, version: %s, resource: %s, namespace: %s, name: %s", *group, *version, *resource, *namespace, *name)
  Error: experiments/compositions/composition/expanders/expand/main.go:40:18: Error return value of `conn.Close` is not checked (errcheck)
  	defer conn.Close()
  	                ^
  Error: experiments/compositions/composition/expanders/expand/main.go:36:15: SA1019: grpc.Dial is deprecated: use NewClient instead.  Will be supported throughout 1.x. (staticcheck)
  	conn, err := grpc.Dial(*addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
  	             ^
  Error: experiments/compositions/composition/pkg/containerexecutor/jobcontainerexecutor/jobcontainerrunner.go:359:17: string `Complete` has 3 occurrences, make it a constant (goconst)
  			if health == "Complete" {
  			             ^
  Error: experiments/compositions/composition/pkg/containerexecutor/jobcontainerexecutor/jobcontainerrunner.go:362:17: string `Failed` has 3 occurrences, make it a constant (goconst)
  			if health == "Failed" {
  			             ^
  experiments/compositions/composition/pkg/containerexecutor/jobcontainerexecutor/jobcontainerrunner.go:67: line is 347 characters (lll)
          args: ["--template", "{{.CompositionName}}", "--plan", "{{.PlanName}}", "--expander", "{{.ExpanderName}}", "--group", "{{.InputAPIGroup}}", "--version", "{{.InputAPIVersion}}", "--resource", "{{.InputAPIResource}}", "--name", "{{.InputAPIName}}", "--namespace", "{{.InputAPINamespace}}", "--path", "/expanded", "--stage", "afterExpansion"]
  experiments/compositions/composition/pkg/containerexecutor/jobcontainerexecutor/jobcontainerrunner.go:82: line is 346 characters (lll)
          args: ["--template", "{{.CompositionName}}", "--plan", "{{.PlanName}}", "--expander", "{{.ExpanderName}}", "--group", "{{.InputAPIGroup}}", "--version", "{{.InputAPIVersion}}", "--resource", "{{.InputAPIResource}}", "--name", "{{.InputAPIName}}", "--namespace", "{{.InputAPINamespace}}", "--path", "/inputs", "--stage", "beforeExpansion"]
  Error: experiments/compositions/composition/tests/cluster/cluster.go:65:38: SA4009: argument v is overwritten before first use (staticcheck)
  		clusterSet.available.Range(func(k, v any) bool {
  		                                   ^
  Error: experiments/compositions/composition/tests/cluster/cluster.go:66:4: SA4009(related information): assignment to v (staticcheck)
  			v, loaded := clusterSet.available.LoadAndDelete(k)
  			^
  Error: experiments/compositions/composition/tests/testclient/client.go:112:13: Error return value of `os.MkdirAll` is not checked (errcheck)
  	os.MkdirAll(path, os.ModePerm)
  	           ^
  Error: experiments/compositions/composition/tests/testclient/client.go:119:14: Error return value of `os.RemoveAll` is not checked (errcheck)
  	os.RemoveAll(path)
  	            ^
  Error: experiments/compositions/composition/tests/testclient/client.go:135:21: Error return value of `podLogs.Close` is not checked (errcheck)
  	defer podLogs.Close()
  	                   ^
  Error: experiments/compositions/composition/tests/testclient/client.go:143:18: Error return value of `file.Close` is not checked (errcheck)
  	defer file.Close()
  	                ^
  experiments/compositions/composition/tests/testclient/client.go:132: line is 217 characters (lll)
  		// client.go:126: Error getting log stream for pod: projectconfigmap-team-a-config-project-4x7nd.copyout container "copyout" in pod "projectconfigmap-team-a-config-project-4x7nd" is waiting to start: PodInitializing
  experiments/compositions/composition/tests/testclient/client.go:283: line is 122 characters (lll)
  					return fmt.Errorf(".condition.message=%s not expected value %s: %w", condition.Message, cond["message"], errMismatch)
  experiments/compositions/composition/tests/testclient/client.go:471: line is 147 characters (lll)
  func (c *Client) recordFailed(op func(*unstructured.Unstructured) error, objs []*unstructured.Unstructured) ([]*unstructured.Unstructured, error) {
  Error: experiments/compositions/composition/tests/testclient/framework.go:45:[33](https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/10392363044/job/28777370178?pr=2503#step:4:35): `getFrequency` - `duration` always receives `opDuration` (`2000000000`) (unparam)
  func getFrequency(t *testing.T, duration, timeout time.Duration) wait.Backoff {
                                  ^
  Error: experiments/compositions/composition/internal/controller/expander_reconciler.go:86:1: cyclomatic complexity 37 of func `(*ExpanderReconciler).Reconcile` is high (> 30) (gocyclo)
  func (r *ExpanderReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
  ^
  Error: experiments/compositions/composition/internal/controller/expander_reconciler.go:333:25: `succesfully` is a misspelling of `successfully` (misspell)
  			logger.Info("Applied succesfully but some resources did not become healthy")
  			                     ^
  Error: experiments/compositions/composition/internal/controller/expander_reconciler.go:4[36](https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/10392363044/job/28777370178?pr=2503#step:4:38):71: `succeded` is a misspelling of `succeeded` (misspell)
  	r.Recorder.Event(cr, "Normal", "ExpansionSucceded", fmt.Sprintf("Job succeded for name: %s", expanderName))
  	                                                                     ^
  Error: experiments/compositions/composition/internal/controller/expander_reconciler.go:6[37](https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/10392363044/job/28777370178?pr=2503#step:4:39):2: Consider pre-allocating `reqs` (prealloc)
  	var reqs []reconcile.Request
  	^
  Error: experiments/compositions/composition/internal/controller/expanderversion_controller.go:112:2: `(*ExpanderVersionReconciler).processExpanderVersion` - `ctx` is unused (unparam)
  	ctx context.Context, ev *compositionv1alpha1.ExpanderVersion, logger logr.Logger,
  	^
  Error: experiments/compositions/composition/internal/controller/expanderversion_controller.go:113:3: (*ExpanderVersionReconciler).processExpanderVersion - result 0 (error) is always nil (unparam)
  ) error {
    ^
  Error: experiments/compositions/composition/internal/controller/expander_reconciler.go:74:5: var `planGVK` is unused (unused)
  var planGVK schema.GroupVersionKind = schema.GroupVersionKind{
      ^
  Error: experiments/compositions/composition/internal/controller/composition_controller.go:209:15: SA1019: grpc.Dial is deprecated: use NewClient instead.  Will be supported throughout 1.x. (staticcheck)
  	conn, err := grpc.Dial(grpcService, grpc.WithTransportCredentials(insecure.NewCredentials()))
  	             ^
  experiments/compositions/composition/expanders/getter/main_test.go:[38](https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/10392363044/job/28777370178?pr=2503#step:4:40)2: line is 156 characters (lll)
  	expectedErrorString := "Field path not present in object yet: Deployment.apps(v1)/composition-system/composition-controller-manager[.spec.template.foobar]"
  Error: experiments/compositions/composition/expanders/getter/main_test.go:69:2: SA1019: rand.Seed has been deprecated since Go 1.20 and an alternative has been available since Go 1.0: As of Go 1.20 there is no reason to call Seed with a random value. Programs that call Seed with a known value to get a specific sequence of results should use New(NewSource(seed)) to obtain a local random generator. (staticcheck)
  	rand.Seed(time.Now().UnixNano())
  	^
  Error: issues found
  Ran golangci-lint in 5[45](https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/10392363044/job/28777370178?pr=2503#step:4:47)30ms
```

**Review by hankfreund — APPROVED** [review]
There's a lot of commented stuff there that seems like it's unnecessary (error messages, command lines, calls to `rand`)... can some of it be cleaned up?

**Comment by barney-s** [comment]
> There's a lot of commented stuff there that seems like it's unnecessary (error messages, command lines, calls to `rand`)... can some of it be cleaned up?

Calls to rand have been cleaned up now. 
Command line comments are useful as documentation. 
Not sure of the error messages that are commented.

**Comment by barney-s** [comment]
All linter errors except 1 has been fixed.

Will send a separate PR for this linter error:
```
internal/controller/expander_reconciler.go:80:1: cyclomatic complexity 37 of func `(*ExpanderReconciler).Reconcile` is high (> 30) (gocyclo)
func (r *ExpanderReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
```

**Pull request merged**
