### PR TITLE
feat:add an expander image version CRD

### PR DESCRIPTION
**Pull request by xiaoweim**
### Change description

This pull request adds a new CRD that
  - maps expanders to their image registry
  - provides a list of valid expander versions

### Tests you have done

run `make e2e-test`

- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [x] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by barney-s** [comment]
How did you generate the files ?

**Comment by xiaoweim** [comment]
> How did you generate the files ?

I ran `make generate` for the deepcopy related methods, and `make` to generate the CRD file. For the hasql Composition CR file, I realized that I missed a expander version in the spec.

**Pull request closed without merging**
