### PR TITLE
Change Terraform Provider in Config Connector repo into a git subtree

### PR DESCRIPTION
**Pull request by diviner524**
### Change description

1. Removed legacy TPG copy under third_party
2. Added TPG 4.84.0 (terraform-provider-google-beta) as the base version of subtree.
3. Applied all legacy patches to the base version as git commits.
4. Removed legacy patches under hack/
5. Update "make ensure" to work with subtree.

For more information on Git subtree:
https://www.atlassian.com/git/tutorials/git-subtree
https://gist.github.com/SKempin/b7857a6ff6bddb05717cc17a44091202

Related document changes will be addressed separately.

Fixes b/303309821

### Tests you have done

- [X] Run `make ready-pr` to ensure this PR is ready for review.
- [N/A] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by justinsb** [comment]
This looks good, but have we figured out how to update the subtree when upstream changes?  That's the tricky thing here, I believe, so I don't think we can punt on that!

**Comment by diviner524** [comment]
> This looks good, but have we figured out how to update the subtree when upstream changes? That's the tricky thing here, I believe, so I don't think we can punt on that!

Yes, so we will do:

`git subtree pull --prefix third_party/github.com/hashicorp/terraform-provider-google-beta https://github.com/hashicorp/terraform-provider-google-beta.git v5.6.0 --squash`

Here is what it looks like, leaving us with 15 files which needs to be manually resolved, merged.

https://paste.googleplex.com/4707212602114048

**Comment by justinsb** [comment]
OK cool.  I assume those 15 merge conflicts are "real" i.e. they were areas we have patched that have also been changed upstream.  In that case, this approach sgtm!

**Comment by diviner524** [comment]
> OK cool. I assume those 15 merge conflicts are "real" i.e. they were areas we have patched that have also been changed upstream. In that case, this approach sgtm!

There are "real" conflicts, and there are some trivial diffs.

"real" conflicts, like below, were caused by our own patch.

https://paste.googleplex.com/6245202633687040


The bunch of edegecontainer conflicts seems unnecessary, I am not sure why git failed to auto-merge them, maybe we can tweak the merge strategy to avoid these? But I assume this won't pop up in every subtree pull once we resolve them.

```
<<<<<<< HEAD
}
=======
}

func expandEdgecontainerVpnConnectionEffectiveLabels(v interface{}, d tpgresource.TerraformResourceData, config *transport_tpg.Config) (map[string]string, error) {
	if v == nil {
		return map[string]string{}, nil
	}
	m := make(map[string]string)
	for k, val := range v.(map[string]interface{}) {
		m[k] = val.(string)
	}
	return m, nil
}
>>>>>>> 1727d000a8c32ccb9d900736b1f6e51489bcf617
```

**Comment by maqiuyujoyce** [comment]
Thanks a lot for the change, @diviner524 !

> `git subtree pull --prefix third_party/github.com/hashicorp/terraform-provider-google-beta https://github.com/hashicorp/terraform-provider-google-beta.git v5.6.0 --squash`

I'm curious, why do we use TPG v5 as the source of truth when updating the subtree? Or is it just a theoretical scenario? 

Besides, context about the patched changes seem to be lost after third_party/Makefile is removed. Can we add a link to this deleted file in the instructions about adding new patches to the TPG subtree (which I assume we will have)?

**Comment by diviner524** [comment]
> Thanks a lot for the change, @diviner524 !
> 
> > `git subtree pull --prefix third_party/github.com/hashicorp/terraform-provider-google-beta https://github.com/hashicorp/terraform-provider-google-beta.git v5.6.0 --squash`
> 
> I'm curious, why do we use TPG v5 as the source of truth when updating the subtree? Or is it just a theoretical scenario?

It is just a theoretical scenario.

> Besides, context about the patched changes seem to be lost after third_party/Makefile is removed. Can we add a link to this deleted file in the instructions about adding new patches to the TPG subtree (which I assume we will have)?

So all the previous patches will become git commits with the context saved as part of the commit message, for example if you click one of the 60+ commits in the PR you will find the related context which used to be part of third_party/Makefile.

Similarly in future we don't add "patches" to the TPG subtree, instead we make changes to the files directly by adding new commits with context in the commit message and related PRs.

**Comment by sofam** [comment]
> > Thanks a lot for the change, @diviner524 !
> > > `git subtree pull --prefix third_party/github.com/hashicorp/terraform-provider-google-beta https://github.com/hashicorp/terraform-provider-google-beta.git v5.6.0 --squash`
> > 
> > 
> > I'm curious, why do we use TPG v5 as the source of truth when updating the subtree? Or is it just a theoretical scenario?
> 
> It is just a theoretical scenario.
> 
> > Besides, context about the patched changes seem to be lost after third_party/Makefile is removed. Can we add a link to this deleted file in the instructions about adding new patches to the TPG subtree (which I assume we will have)?
> 
> So all the previous patches will become git commits with the context saved as part of the commit message, for example if you click one of the 60+ commits in the PR you will find the related context which used to be part of third_party/Makefile.
> 
> Similarly in future we don't add "patches" to the TPG subtree, instead we make changes to the files directly by adding new commits with context in the commit message and related PRs.

Awesome! This will make it a little bit easier to contribute!

**Pull request merged**
