### PR TITLE
chore: skip update client in ready-pr

### PR DESCRIPTION
**Pull request by yuwenma**
related to #3037

### CODE REVIEW

**Comment by maqiuyujoyce** [comment]
/lgtm
/approve

Do we plan to remove the go client generated by `make generate-go-client` soon?

**Comment by yuwenma** [comment]
> /lgtm /approve
> 
> Do we plan to remove the go client generated by `make generate-go-client` soon?

We don't. Here's more details about [the plan](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/pkg/clients/generated/README.md). I will announce it in 1.126 release.

**Comment by maqiuyujoyce** [comment]
Sounds good.

**Pull request merged**
