### PR TITLE
Move upgrade-kcc target to GitHub to prepare for next release

### PR DESCRIPTION
**Pull request by diviner524**
### Change description

This Makefile target is required to upgrade operator artifacts (which are now in this GitHub repository) and prepare for a new operator release.

Fixes b/303883337

### Tests you have done

- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [N/A] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Review by jingyih — COMMENTED** [review]
/lgtm

**Comment by diviner524** [comment]
//hold cancel

**Pull request merged**
