### PR TITLE
regen: fix head

### PR DESCRIPTION
**Pull request by acpana**
I think https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3398 upset the `make manifest` for this resource.

### CODE REVIEW

**Review by jingyih — COMMENTED** [review]
/lgtm

Looks like my PR has a conflict after #3414 is merged. I am closing #3418 in favor of this.

**Comment by maqiuyujoyce** [comment]
/approve
/hold
Hold as @yuwenma wants to track the merge of PRs.

**Review by yuwenma — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
