### PR TITLE
Replace 'requesterJustificationConfig' with 'requesterJustificationType' in PAMEntitlement

### PR DESCRIPTION
**Pull request by maqiuyujoyce**
### Change description

`spec.requesterJustificationConfig` doesn't provide a good UX for users to pick the justification type: the object types are field-less, and users must pick one subfield and set the value to `{}`, a value without explicit meaning. So we decided to replace it with `spec.requesterJustificationType` for a more declarative UX.

### Tests you have done

- [X] Run `make ready-pr` to ensure this PR is ready for review.
- [X] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by yuwenma** [comment]
Will the typed field be extended?

**Comment by maqiuyujoyce** [comment]
> Will the typed field be extended?

@yuwenma Did you mean to ask whether there will be more accepted types of requester justifications? Or did you ask about the extension of the originally field-less types for NotMandatory and Unstructured?

**Comment by yuwenma** [comment]
> @yuwenma Did you mean to ask whether there will be more accepted types of requester justifications? Or did you ask about the extension of the originally field-less types for NotMandatory and Unstructured?

I'm more thinking about the following possibilities: 
```yaml
spec:
   requesterJustificationConfig:
       notMandatory:
            foo1: # 1. has sub fields. This seems to be reasonable considering the the NotMandatory struct type.
            foo2:
       unstructured: # 2. both fields are configured, which seems to be fine becuase "notMandatory" and "unstructured" seems to be orthogonal configs.
            bar1: 
            bar2: 
```

**Comment by maqiuyujoyce** [comment]
> > @yuwenma Did you mean to ask whether there will be more accepted types of requester justifications? Or did you ask about the extension of the originally field-less types for NotMandatory and Unstructured?
> 
> I'm more thinking about the following possibilities:
> 
> ```yaml
> spec:
>    requesterJustificationConfig:
>        notMandatory:
>             foo1: # 1. has sub fields. This seems to be reasonable considering the the NotMandatory struct type.
>             foo2:
>        unstructured: # 2. both fields are configured, which seems to be fine becuase "notMandatory" and "unstructured" seems to be orthogonal configs.
>             bar1: 
>             bar2: 
> ```

For the 1st concern, yes, the feature will possibly be extended like this. It will be supported by adding `requesterJustificationConfig`,  `notMandatory` and `unstructured` as optional fields.

For the 2nd concern, afaik, `notMandatory` and `unstructured` are mutually exclusive. Will follow up offline to get confirmation from the service team.

**Comment by maqiuyujoyce** [comment]
Discussed offline and decided this change is not necessary.

**Pull request closed without merging**
