### PR TITLE
Add mocks for EdgeContainerCluster and EdgeContianerNodePool

### PR DESCRIPTION
**Pull request by gemmahou**
### Change description

Fixes b/311655406

EdgeContainerNodePool will be disabled due to special requirements from service team. Create mock test to cover it. 

### Tests you have done
```
--- PASS: TestAllInSeries (35.35s)
    --- PASS: TestAllInSeries/fixtures (24.51s)
        --- PASS: TestAllInSeries/fixtures/edgecontainernodepool (24.26s)
PASS
ok      github.com/GoogleCloudPlatform/k8s-config-connector/tests/e2e   35.541s
```

```
--- PASS: TestAllInSeries (34.56s)
    --- PASS: TestAllInSeries/fixtures (23.46s)
        --- PASS: TestAllInSeries/fixtures/edgecontainercluster (23.23s)
PASS
ok      github.com/GoogleCloudPlatform/k8s-config-connector/tests/e2e   34.744s
```

- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [x] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Review by rayccz2 — APPROVED** [review]

**Comment by justinsb** [comment]
Thanks @gemmahou 

/approve
/lgtm

**Comment by justinsb** [comment]
I think it's the samples are failing (not the fixtures):

`ARTIFACTS=`pwd`/artiacts/ RUN_E2E=1 E2E_KUBE_TARGET=envtest E2E_GCP_TARGET=mock go test -test.count=1 -v ./tests/e2e -run TestAllInSeries/samples/edgecontainercluster  2>&1 | tee log` =>
```
{"severity":"info","timestamp":"2023-11-22T16:20:22.276-0500","msg":"done processing request","operation":"CREATE","handler":"management conflict annotation defaulter","kind":"EdgeContainerCluster","resource":{"namespace":"mock-project","name":"edgecontainercluster-local-control-plane-sample"}}
    samples.go:110: error creating resource: EdgeContainerCluster.edgecontainer.cnrm.cloud.google.com "edgecontainercluster-local-control-plane-sample" is invalid: spec.externalLoadBalancerIpv4AddressPools: Invalid value: "string": spec.externalLoadBalancerIpv4AddressPools in body must be of type array: "string"

```

`ARTIFACTS=`pwd`/artiacts/ RUN_E2E=1 E2E_KUBE_TARGET=envtest E2E_GCP_TARGET=mock go test -test.count=1 -v ./tests/e2e -run TestAllInSeries/samples/edgecontainernodepool  2>&1 | tee log` =>

```
{"severity":"info","timestamp":"2023-11-22T16:21:31.187-0500","msg":"done processing request","operation":"CREATE","handler":"management conflict annotation defaulter","kind":"EdgeContainerCluster","resource":{"namespace":"mock-project","name":"edgecontainercluster-local-control-plane-dep"}}
    samples.go:110: error creating resource: EdgeContainerCluster.edgecontainer.cnrm.cloud.google.com "edgecontainercluster-local-control-plane-dep" is invalid: spec.externalLoadBalancerIpv4AddressPools: Invalid value: "string": spec.externalLoadBalancerIpv4AddressPools in body must be of type array: "string"
```

**Comment by gemmahou** [comment]
> I think it's the samples are failing (not the fixtures):
> 
> ```
> ARTIFACTS=`pwd`/artifacts/ RUN_E2E=1 E2E_KUBE_TARGET=envtest E2E_GCP_TARGET=mock go test -test.count=1 -v ./tests/e2e -run TestAllInSeries/samples/edgecontainercluster  2>&1 | tee log
> ```
> 
> =>
> 
> ```
> {"severity":"info","timestamp":"2023-11-22T16:20:22.276-0500","msg":"done processing request","operation":"CREATE","handler":"management conflict annotation defaulter","kind":"EdgeContainerCluster","resource":{"namespace":"mock-project","name":"edgecontainercluster-local-control-plane-sample"}}
>     samples.go:110: error creating resource: EdgeContainerCluster.edgecontainer.cnrm.cloud.google.com "edgecontainercluster-local-control-plane-sample" is invalid: spec.externalLoadBalancerIpv4AddressPools: Invalid value: "string": spec.externalLoadBalancerIpv4AddressPools in body must be of type array: "string"
> ```
> 
> ```
> ARTIFACTS=`pwd`/artifacts/ RUN_E2E=1 E2E_KUBE_TARGET=envtest E2E_GCP_TARGET=mock go test -test.count=1 -v ./tests/e2e -run TestAllInSeries/samples/edgecontainernodepool  2>&1 | tee log
> ```
> 
> =>
> 
> ```
> {"severity":"info","timestamp":"2023-11-22T16:21:31.187-0500","msg":"done processing request","operation":"CREATE","handler":"management conflict annotation defaulter","kind":"EdgeContainerCluster","resource":{"namespace":"mock-project","name":"edgecontainercluster-local-control-plane-dep"}}
>     samples.go:110: error creating resource: EdgeContainerCluster.edgecontainer.cnrm.cloud.google.com "edgecontainercluster-local-control-plane-dep" is invalid: spec.externalLoadBalancerIpv4AddressPools: Invalid value: "string": spec.externalLoadBalancerIpv4AddressPools in body must be of type array: "string"
> ```

externalLoadBalancerIpv4AddressPools should be an array, updated to: 
```
  externalLoadBalancerIpv4AddressPools:
    - ${EXTERNAL_LOAD_BALANCER_IPV4_CIDR?}
```
and verified locally.

**Comment by justinsb** [comment]
Thanks @gemmahou  - lgtm!

/approve
/lgtm

cc @rayccz2 - as we are tweaking the samples a bit here!

**Pull request merged**
