### PR TITLE
mockgcp: don't depend on "root" module

### PR DESCRIPTION
**Pull request by justinsb**
Introduce mocks/pointerutils.go to avoid depending on the "root" module.

Depending on the root creates a circular dependency, because the root
depends on the mockgcp module.  This in turn breaks `go mod tidy` and
friends, because the root module contains an import override.

### CODE REVIEW

**Comment by acpana** [comment]
/lgtm
/approve

great catch! We (I) should write a rule against these kind of imports.

**Comment by justinsb** [comment]
> We (I) should write a rule against these kind of imports.
I think just run `go mod tidy` in mockgcp catches it ... suggesting we probably aren't doing that today

**Pull request merged**
