### PR TITLE
chore: create a (placeholder) CI task

### PR DESCRIPTION
**Pull request by justinsb**
This script doesn't do anything yet, but we can start to add the
wiring for running it.

### CODE REVIEW

**Comment by justinsb** [comment]
cc @xiaoweim - this is the (placeholder) CI script that we can wire up

**Comment by xiaoweim** [comment]
Hi @justinsb, I want to clarify that did you tag me for reference of the script that we might have, or is this task assigned to me for me to work on it? And It seems like that I cannot be assigned because of permission issue?

**Comment by justinsb** [comment]
I think we have other CI jobs now

/close

**Pull request closed without merging**
