### PR TITLE
Create very simple test for operators

### PR DESCRIPTION
**Pull request by justinsb**
- Add e2e test for ConfigConnector operator
- operator: build scheme once and reuse in tests

### CODE REVIEW

**Comment by justinsb** [comment]
We do need to make sure this fails tests, at first, given that we think that we need https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/368

**Comment by justinsb** [comment]
Failing as expected:

```
=== NAME  TestE2E
    e2e_test.go:75: unexpected value for status.healthy: got 'false', want 'true'
    e2e_test.go:78: unexpected number of errors in status.errors: got 1, want 0. Got errors: [error during reconciliation: no matches for kind "" in version ""]
--- FAIL: TestE2E (25.25s)
```

**Comment by justinsb** [comment]
Should now be passing after kdp upgrade :crossed_fingers:

**Review by maqiuyujoyce — APPROVED** [review]
LGTM except for a few unblocking questions!

**Pull request merged**
