### PR TITLE
doc(README): remove typo

### PR DESCRIPTION
**Pull request by RahulK4102**
## Description:

This Pull Request fixes a typographical error in the README.md file.

## Changes Made:

 - Corrected "inlcudes" to "includes" in the README.md file.

## Additional Information:

This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.

Thank you for considering this contribution.

### CODE REVIEW

**Comment by diviner524** [comment]
@RahulK4102 Thank you for the fix! 

Note as we are currently a Google open source project, you will need to sign CLA to get this PR approved.

**Comment by RahulK4102** [comment]
> @RahulK4102 Thank you for the fix!
> 
> Note as we are currently a Google open source project, you will need to sign CLA to get this PR approved.

I have signed the CLA

**Review by diviner524 — COMMENTED** [review]
/lgtm

**Pull request merged**
