### PR TITLE
chore: generate logginglogmetric krm exports

### PR DESCRIPTION
**Pull request by acpana**
Sample commands used for generation:

```bash
$ WRITE_GOLDEN_OUTPUT=1 GOLDEN_OBJECT_CHECKS=1 BILLING_ACCOUNT_ID="REDACTED" ORGANIZATION_ID="REDACTED" E2E_KUBE_TARGET=envtest RUN_E2E=1 E2E_GCP_TARGET=real go test -test.count=1 -timeout 600s -v ./tests/e2e -run TestAllInSeries/fixtures/linearlogmetric
```

### CODE REVIEW

**Comment by gemmahou** [comment]
I made the change in #1447, but looking at the golden files, I think we may not need to have the test name in the file name because we place the golden file under its corresponding test folder, so we know it belongs to that test.

i.e.
Before: logginglogmetric/explicitlogmetric/_generated_object_explicitlogmetric.golden.yaml
After: logginglogmetric/explicitlogmetric/_generated_object.golden.yaml

Would like to hear your opinion, @justinsb.

If we agree on this, I can make the code change and regenerate files very quick. And let's hold this PR for now. Sorry for the inconvenience, I feel as we have more generated files, we'll need to create a documentation about the naming and the usage of them.

**Comment by justinsb** [comment]
Agreed on the naming being something we should change, and I think a code comment where we write the files is all we need.  I think a reasonable name is probably:  `{fixture.SourceDir}/_objects/{kind}_{name}.yaml` (sticking to the convention proposed in another PR that generated files start with `_` or are in a directory that starts with `_`).   I think `{fixture.SourceDir}/_object_{kind}_{name}.yaml` would also work.  But happy to riff on ideas (e.g. do we need the namespace?)  I think that's a separate PR thought.

I don't know that we need to hold this PR, as long as @acpana is willing to rename the golden files (or just regenerate them).  I think the github diff tooling will detect them as a rename if they are just renames (and can detect diffs across renames with small changes).

**Comment by acpana** [comment]
Happy to rename (and regenerate) the files to the new format -- should that be done as part of this PR ?

**Comment by justinsb** [comment]
> Happy to rename (and regenerate) the files to the new format -- should that be done as part of this PR ?

Either way, as you prefer.  I'll approve and hold and you can decide.  I think @gemmahou 's PRs to move the vcr test output have now landed.

/approve
/lgtm
/hold

**Comment by acpana** [comment]
let me pull this in and follow up as needed 🙏🏼 

/hold cancel

**Pull request merged**
