### PR TITLE
tests: err out if skeleton non null

### PR DESCRIPTION
**Pull request by acpana**
Related to #2135

### CODE REVIEW

**Comment by acpana** [comment]
Current offenders:

```
    resourceskeleton_test.go:76: error skeleton is not null but resource doesn't support NewFromUri 'CertificateManagerCertificate': https://certificatemanager.googleapis.com/v1/projects/kcc-test/locations/europe-west1/certificates/certificate-test?alt=json
    resourceskeleton_test.go:76: error skeleton is not null but resource doesn't support NewFromUri 'CertificateManagerCertificateMap': https://certificatemanager.googleapis.com/v1/projects/kcc-test/locations/global/certificateMaps/certificatemap-test?alt=json
    resourceskeleton_test.go:76: error skeleton is not null but resource doesn't support NewFromUri 'CertificateManagerCertificateMapEntry': https://certificatemanager.googleapis.com/v1/projects/kcc-test/locations/global/certificateMaps/certificatemap-test/certificateMapEntries/certificatemapentry-test?alt=json
    resourceskeleton_test.go:76: error skeleton is not null but resource doesn't support NewFromUri 'CertificateManagerDNSAuthorization': https://certificatemanager.googleapis.com/v1/projects/kcc-test/locations/global/dnsAuthorizations/dnsauthorization-test?alt=json
    resourceskeleton_test.go:76: error skeleton is not null but resource doesn't support NewFromUri 'EdgeContainerCluster': https://edgecontainer.googleapis.com/v1/projects/kcc-test/locations/us-central1/clusters/edgecontainercluster-test
    resourceskeleton_test.go:76: error skeleton is not null but resource doesn't support NewFromUri 'EdgeContainerNodePool': https://edgecontainer.googleapis.com/v1/projects/kcc-test/locations/us-central1/clusters/edgecontainercluster-test/nodePools/edgecontainernodepool-test
    resourceskeleton_test.go:76: error skeleton is not null but resource doesn't support NewFromUri 'EdgeContainerVpnConnection': https://edgecontainer.googleapis.com/v1/projects/kcc-test/locations/us-central1/vpnConnections/edgecontainervpnconnection-test
    resourceskeleton_test.go:76: error skeleton is not null but resource doesn't support NewFromUri 'VertexAIDataset': https://us-central1-aiplatform.googleapis.com/v1beta1/projects/kcc-test/locations/us-central1/datasets/1234567890?alt=json
    resourceskeleton_test.go:76: error skeleton is not null but resource doesn't support NewFromUri 'VertexAIEndpoint': https://us-central1-aiplatform.googleapis.com/v1beta1/projects/kcc-test/locations/us-central1/endpoints/vertexaiendpoint-test
    resourceskeleton_test.go:76: error skeleton is not null but resource doesn't support NewFromUri 'VertexAIIndex': https://us-central1-aiplatform.googleapis.com/v1beta1/projects/kcc-test/locations/us-central1/indexes/vertexaiindex-test
    resourceskeleton_test.go:76: error skeleton is not null but resource doesn't support NewFromUri 'CloudIDSEndpoint': https://ids.googleapis.com/projects/kcc-test/locations/us-west2-a/endpoints/cloudidsendpoint-ppdtifqxy4vqi4ezx7la
    resourceskeleton_test.go:76: error skeleton is not null but resource doesn't support NewFromUri 'ComputeManagedSSLCertificate': https://www.googleapis.com/compute/v1/projects/kcc-test/global/sslCertificates/computemanagedsslcertificate-wj6kvvmztb67xscbzd5a
```

**Comment by jingyih** [comment]
Attempting to fix Vertex AI resources in #2244.

**Review by maqiuyujoyce — COMMENTED** [review]
Thank you for adding the check!

/lgtm
/approve

**Pull request merged**
