### PR TITLE
mockgcp: support for LoggingLogBucket

### PR DESCRIPTION
**Pull request by justinsb**
- tests: captured test output for projectlogbucket
- mockgcp: add support for LoggingLogBucket
- mockgcp: Allow services to rewrite errors for accurate golden testing

### CODE REVIEW

**Comment by justinsb** [comment]
/assign @acpana 

(Also ... ask me for the backstory here!)

**Comment by acpana** [comment]
This LGTM overall but I think the test harness is coming to our rescue! Digging into the logs I see that test failures for

```
* 1. TestAllInSeries/samples/organization-log-bucket
* 2. TestAllInSeries/samples/billing-account-log-bucke
```

may actually be genuine: 

```
1.  Error 400: name \"organizations/123450001/locations/global/buckets/_Default\" is not valid"}
2. .. resource reference is missing required 'name' field"} ...
```

sample run: https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/8648481995/job/23786979096?pr=1545

**Comment by justinsb** [comment]
Rebased and added more of the cases covered in our samples to mockgcp!

**Comment by acpana** [comment]
thanks for following up here 🥇 🙏🏼 

/lgtm
/approve

**Pull request merged**
