### PR TITLE
Change location for basicalloydbcluster test

### PR DESCRIPTION
**Pull request by anhdle-sso**
### Change description

Change location for basicalloydbcluster test

### Tests you have done

- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [x] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by justinsb** [comment]
LGTM, but can we document why we're changing the region?

A comment on this thread will suffice, but ideally a comment on create.yaml

/approve
/lgtm
/hold (for comment)

**Comment by maqiuyujoyce** [comment]
I assume this PR is based on changes in #1739, right?

/lgtm

**Comment by anhdle-sso** [comment]
> I assume this PR is based on changes in #1739, right?
> 
> /lgtm

yes. it is requested by the alloydb team.

**Pull request merged**
