### PR TITLE
versionbump: update prometheus-to-sd image

### PR DESCRIPTION
**Pull request by justinsb**
Updating to newest version

### CODE REVIEW

**Comment by maqiuyujoyce** [comment]
Just curious, why is it blocking 1.114.0?

**Comment by justinsb** [comment]
> Just curious, why is it blocking 1.114.0?

CVEs (real or imaginary)

**Comment by maqiuyujoyce** [comment]
> CVEs (real or imaginary)

Gotcha. I think the CVEs were fixed in our code. It's just pending a component release and etc.

**Pull request merged**
