### PR TITLE
Support the `spec.configmanagement.configSync.stopSyncing` field in GKEHubFeatureMembership

### PR DESCRIPTION
**Pull request by haiyanmeng**
### Change description

This adds the support for the `spec.configmanagement.configSync.stopSyncing` field into the resource `GKEHubFeatureMembership`. 

This PR needs a release note.

### Tests you have done

```
E2E_KUBE_TARGET=envtest RUN_E2E=1 E2E_GCP_TARGET=mock WRITE_GOLDEN_OUTPUT=1 GOLDEN_REQUEST_CHECKS=1 GOLDEN_OBJECT_CHECKS=1 go test -test.count=1 -timeout 1000s -v ./tests/e2e -run 'TestAllInSeries/fixtures/gkehubfeaturemembership|TestAllInSeries/fixtures/gkehubfeaturemembership'
```

- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [ ] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Review by yuwenma — COMMENTED** [review]
/approve

Thanks! Assigned to @acpana for another pass for GKEHub resources.

**Comment by haiyanmeng** [comment]
@yuwenma , I saw you put the PR on hold. Are there any action items for me?

**Comment by yuwenma** [comment]
> @yuwenma , I saw you put the PR on hold. Are there any action items for me?

No action items. I just want to make sure @acpana  can take a look before it merges.

**Review by acpana — COMMENTED** [review]
/lgtm
/approve

thanks for the change 🥇

**Pull request merged**
