### PR TITLE
tests: try introducing a subtest timeout to unified_test

### PR DESCRIPTION
**Pull request by justinsb**
We would like to fail fast on individual tests; with our mocks no test
should take very long.

### CODE REVIEW

**Comment by justinsb** [comment]
OK, that was a lucky test failure.  It would have been a timeout on certificatemanagercertificatemapentry, but the timeout kicked in.  I would like to see something clearer than "parent context cancelled" though, so going to give it another try...

**Comment by justinsb** [comment]
Hooray - a fairly rapid timeout:


```
2024-02-28T02:10:05.8240593Z     samples.go:230: error while polling for resource cleanup on CertificateManagerCertificateMapEntry with name 'certificatemanagercertificatemapentry-sample': context deadline exceeded; last seen status: map[conditions:[map[lastTransitionTime:2024-02-28T02:09:25Z message:Delete call failed: error fetching live state: error getting ID for resource: error getting value from reference: could not parse reference resolution value '<nil>' as string reason:DeleteFailed status:False type:Ready]] observedGeneration:3 state:SERVING_STATE_UNSPECIFIED]
2024-02-28T02:10:05.8245645Z     harness.go:347: waiting for controller-runtime manager shutdown
2024-02-28T02:10:05.8246786Z     harness.go:349: controller-runtime manager is shutdown
2024-02-28T02:10:06.9805038Z     unified_test.go:365: subtest timeout after 1m0s
....
 --- FAIL: TestAllInSeries/samples/certificatemanagercertificatemapentry (61.83s)
 ```

So that is WAI - timing out after about a minute.

**Comment by justinsb** [comment]
/assign @gemmahou 

This is a simple idea, but annoyingly tricky to implement (though not too many lines of code!).  There's a proposal to just have a SetTimeout method on the subtest but no real progress yet.  

But I think it's good because it should stop our mocks timing out in github, we'll force-fail any individual test after a minute, so we can see the test failures clearly.  In contrast, when the whole test times out we normally just get a panic and we don't get the `PASS:` / `FAIL:` block

We might raise the time limit e.g. to two minutes in future, but TBH they're already taking longer than I think they should anyway, so I'm hoping we could look at why they are slow (it might be the terraform reconciliation logic having built-in delays)

**Comment by gemmahou** [comment]
Thanks for introducing timeout for individual tests!

/lgtm
/approve

**Comment by justinsb** [comment]
Thanks @gemmahou ... needs another lgtm after rebase I'm afraid!

**Comment by gemmahou** [comment]
The presubmit tests start failing after rebase...

**Comment by justinsb** [comment]
> The presubmit tests start failing after rebase...
Yeah ... we could really use a submit queue :-)

**Comment by gemmahou** [comment]
/lgtm
/approve

thanks! i think the timeout will be useful for vcr testing as well.

**Pull request merged**
