### PR TITLE
Temporarily skip compute service attachment tests

### PR DESCRIPTION
**Pull request by gemmahou**
### Change description

Fixes https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/2621

Context: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2620

### Tests you have done

- [ ] Run `make ready-pr` to ensure this PR is ready for review.
- [ ] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by yuwenma** [comment]
Can you share more context about why skipping this test?

**Comment by gemmahou** [comment]
> Can you share more context about why skipping this test?

Yeah, more context: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2620

**Comment by yuwenma** [comment]
Okay, I see this blocks the presubmit PRs.  Let's get it go in to unblock other PRs to checkin, and then we can fix.

**Pull request merged**
