### PR TITLE
tests: add more StorageBucket tests

### PR DESCRIPTION
**Pull request by justinsb**
Covering softDeletePolicy.retentionDurationSeconds in particular.

### CODE REVIEW

**Comment by justinsb** [comment]
I think we're also going to need some with state-into-spec: absent, but this PR is already getting pretty big...

**Comment by yuwenma** [comment]
/lgtm

Looks like we need to re-generate the http log.

**Comment by yuwenma** [comment]
/approve 

PR looks good. 
The failed VCR test is for `sourcereporepository` but I don't see how that's related.  I reran the test. hope it can pass.

**Pull request merged**
