### PR TITLE
feat: add mockgcp for bigqueryroutine

### PR DESCRIPTION
**Pull request by xiaoweim**
- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [x] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Review by yuwenma — COMMENTED** [review]
This looks good. Can I ask for a git-commit that shows the http log against real GCP (maybe as the very first git-commit) and then the second git-commit can run against the mock gcp?

**Comment by xiaoweim** [comment]
> This looks good. Can I ask for a git-commit that shows the http log against real GCP (maybe as the very first git-commit) and then the second git-commit can run against the mock gcp?

I have updated the PR with git commits showing the real/mock GCP logs, could you take another look @yuwenma ? Thank you!

**Comment by jingyih** [comment]
In the http log, I don't see any "PATCH" requests for the bigqueryroutine, is the resource being updated in the test?

**Comment by xiaoweim** [comment]
> In the http log, I don't see any "PATCH" requests for the bigqueryroutine, is the resource being updated in the test?

No, the `update.yaml` file are the same as `create.yaml`. My understanding is that I will have a second PR using git-commit to show the update log, and that's where I change the `update.yaml` file

**Comment by jingyih** [comment]
> > In the http log, I don't see any "PATCH" requests for the bigqueryroutine, is the resource being updated in the test?
> 
> No, the `update.yaml` file are the same as `create.yaml`. My understanding is that I will have a second PR using git-commit to show the update log, and that's where I change the `update.yaml` file

Could you add a separate commit to this PR to update the `update.yaml` file and the http logs? A separate commit should be sufficient, it doesn't necessarily need to be in a separate PR.

**Review by jingyih — COMMENTED** [review]
/lgtm

**Comment by acpana** [comment]
Is this causing the recent presubmit failures?

```
024-12-03T08:27:11.8996030Z     utils.go:149: FAIL: unexpected diff in /home/runner/work/k8s-config-connector/k8s-config-connector/pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/basicbigqueryroutine/_http.log:   (
2024-12-03T08:27:11.9000225Z           	"""
2024-12-03T08:27:11.9000851Z           	... // 59 identical lines
2024-12-03T08:27:11.9001522Z           	  "access": [
2024-12-03T08:27:11.9002034Z           	    {
2024-12-03T08:27:11.9002407Z         - 	      "role": "WRITER",
2024-12-03T08:27:11.9002909Z         - 	      "specialGroup": "projectWriters"
2024-12-03T08:27:11.9003376Z         + 	      "role": "OWNER",
2024-12-03T08:27:11.9003924Z         + 	      "specialGroup": "projectOwners"
2024-12-03T08:27:11.9004416Z           	    },
2024-12-03T08:27:11.9004709Z           	    {
2024-12-03T08:27:11.9005124Z           	      "role": "OWNER",
2024-12-03T08:27:11.9005594Z         - 	      "specialGroup": "projectOwners"
2024-12-03T08:27:11.9006102Z         + 	      "userByEmail": "user@google.com"
2024-12-03T08:27:11.9006398Z           	    },
2024-12-03T08:27:11.9006611Z           	    {
2024-12-03T08:27:11.9006850Z         - 	      "role": "OWNER",
2024-12-03T08:27:11.9007186Z         - 	      "userByEmail": "user@google.com"
2024-12-03T08:27:11.9007511Z         + 	      "role": "READER",
2024-12-03T08:27:11.9007853Z         + 	      "specialGroup": "projectReaders"
2024-12-03T08:27:11.9008145Z           	    },
2024-12-03T08:27:11.9008362Z           	    {
2024-12-03T08:27:11.9008611Z         - 	      "role": "READER",
2024-12-03T08:27:11.9009051Z         - 	      "specialGroup": "projectReaders"
2024-12-03T08:27:11.9009383Z         + 	      "role": "WRITER",
2024-12-03T08:27:11.9009722Z         + 	      "specialGroup": "projectWriters"
2024-12-03T08:27:11.9010020Z           	    }
2024-12-03T08:27:11.9010230Z           	  ],
```

from https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/12135538398/job/33834795927

**Comment by jingyih** [comment]
Possibly. Based on the test logs, the presubmit tests on this PR were last run about a month ago. If the related mock service has been updated since then, it might cause HEAD to break.

From [tests-e2e-fixtures](https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/11717624055/job/32637591866#logs):
```
2024-11-07T06:13:43.6911273Z Current runner version: '2.320.0'
...
```

**Pull request merged**
