### PR TITLE
feat: trigger ssa metadata for direct controller

### PR DESCRIPTION
**Pull request by acpana**
Following the DCL/ TF controllers to trigger ssa metadata annotation.

### CODE REVIEW

**Comment by maqiuyujoyce** [comment]
I traced back to the change when [TriggerManagedFieldsMetadata](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/pkg/k8s/meta.go) was added. It looks like this is used to enable the externally managed fields on clusters between K8s 1.16 and 1.18 because the metadata is not automatically triggered. 

I think it'll be safe if we keep it; though @yuwenma do you think it'll be more sustainable if we keep track of versions of clusters where Config Connector is installed so that we can clean up version-specific logic over time?

**Comment by yuwenma** [comment]
I would say may be not a necessity. But I'm not very familiar with the KCC `cnrm.cloud.google.com/supports-ssa` annotation. By reading its doc https://cloud.google.com/config-connector/docs/concepts/managing-fields-externally#behavior_with_server-side_apply, it is not clear to me how it works with the k8s server-side apply.  @justinsb would you mind justifying?

**Comment by justinsb** [comment]
As far as I can tell we never read this annotation nor the field manager.  I concur with @maqiuyujoyce that this is not needed in modern k8s version, where you basically always have managedFields.  Also, given that we aren't using managedFields in our direct controllers (at least not yet), I don't think we need this annotation.  If it turns out we do need it, we can always add it later.

**Comment by justinsb** [comment]
/hold

Because I don't think we want this in 1.118.  If people agree, not sure if we move to 1.119 or just close?

**Comment by maqiuyujoyce** [comment]
Yeah I'm okay with not having it as we can always add it if there are some unexpected issues.
Regarding `cnrm.cloud.google.com/supports-ssa`, I never had to interact with this annotation. But we should update the public doc to reflect our change: https://cloud.google.com/config-connector/docs/reference/annotations

**Comment by yuwenma** [comment]
Close the PR to clear up the PR review list. We can re-open this PR if the question comes up to the table in the future.

**Pull request closed without merging**
