### PR TITLE
WIP: Add FirestoreDatabase direct controller

### PR DESCRIPTION
**Pull request by jasonvigil**
Based on example in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2573

### CODE REVIEW

**Comment by jingyih** [comment]
Hi @jasonvigil, are you seeing similar issues when generating the types as mentioned in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2573#issuecomment-2313731858?

**Comment by jasonvigil** [comment]
@jingyih 

> Hi @jasonvigil, are you seeing similar issues when generating the types as mentioned in [#2573 (comment)](https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2573#issuecomment-2313731858)?

I think so. There are quite a few extra resources (besides `Database`) generated in `types.generated.go`. Though I am not sure if that is intentional (?)

**Comment by jingyih** [comment]
I updated the implementation of type generator in #2573. Would like to see if that works better for your resource.

**Comment by jasonvigil** [comment]
Thank you @jingyih! Pulled in your changes. It no longer generates extra resources.

**Pull request closed without merging**
