### PR TITLE
fix: update the compute image test yaml

### PR DESCRIPTION
**Pull request by xiaoweim**
The bucket was deleted and rendered the test to fail. Updated the yaml with new bucket and tested locally.

- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [x] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by yuwenma** [comment]
PR look good. Could you run `make ready-pr` to fix the presubmit check?

**Comment by cheftako** [comment]
I1025 01:11:17.912225   33284 main.go:169] skipping alpha resource bigqueryanalyticshub.cnrm.cloud.google.com/v1alpha1, Kind=BigQueryAnalyticsHubListing
Full diff:
diff --git a/scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeimage.md b/scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeimage.md
index 9495eafc7..35334a952 100644
--- a/scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeimage.md
+++ b/scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeimage.md
@@ -703,7 +703,7 @@ spec:
   family: ubuntu-custom
   licenses: ["https://compute.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx"]
   rawDisk:
-    source: "https://storage.googleapis.com/bosh-gce-raw-stemcells/bosh-stemcell-97.98-google-kvm-ubuntu-xenial-go_agent-raw-1557960142.tar.gz"
+    source: "https://storage.googleapis.com/cnrm-test-computeimage-raw/computeimage-raw.tar.gz"
     containerType: "TAR"
     sha1: [819](https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/11509947917/job/32041008894?pr=3005#step:4:820)b7e9c17423f4539f09687eaa13687afa2fe32

**Comment by xiaoweim** [comment]
> PR look good. Could you run `make ready-pr` to fix the presubmit check?

Yes, just updated it!

**Comment by xiaoweim** [comment]
> I1025 01:11:17.912225 33284 main.go:169] skipping alpha resource bigqueryanalyticshub.cnrm.cloud.google.com/v1alpha1, Kind=BigQueryAnalyticsHubListing Full diff: diff --git a/scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeimage.md b/scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeimage.md index 9495eafc7..35334a952 100644 --- a/scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeimage.md +++ b/scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeimage.md @@ -703,7 +703,7 @@ spec: family: ubuntu-custom licenses: ["https://compute.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx"] rawDisk:
> 
> * source: "https://storage.googleapis.com/bosh-gce-raw-stemcells/bosh-stemcell-97.98-google-kvm-ubuntu-xenial-go_agent-raw-1557960142.tar.gz"
> 
> * source: "https://storage.googleapis.com/cnrm-test-computeimage-raw/computeimage-raw.tar.gz"
>   containerType: "TAR"
>   sha1: [819](https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/11509947917/job/32041008894?pr=3005#step:4:820)b7e9c17423f4539f09687eaa13687afa2fe32

Updated the PR!

**Comment by maqiuyujoyce** [comment]
@xiaoweim I have a couple of thoughts regarding the change:

1. Pre-established resource names (project, network, etc) should not be exposed/hard-coded in our OSS code, but instead, should be represented by place holders.
2. It's a question to our team whether we want this image to be accessed by the external users (i.e. making it public). If we don't want to do so, this value should be replaced by the place holder. If we do want to make it public, we should probably use a project name that doesn't contain internal information.

**Comment by xiaoweim** [comment]
> @xiaoweim I have a couple of thoughts regarding the change:
> 
> 1. Pre-established resource names (project, network, etc) should not be exposed/hard-coded in our OSS code, but instead, should be represented by place holders.
> 2. It's a question to our team whether we want this image to be accessed by the external users (i.e. making it public). If we don't want to do so, this value should be replaced by the place holder / environment variable. If we do want to make it public, we should probably use a project name that doesn't contain internal information.

For point 1, does it apply to our test yamls file and doc files as well?
For point 2, currently this image is not public in the testing project, I copied this image over from `gs://configconnector-operator/latest/release-bundle.tar.gz`, this image is a public image used for config connector manual installation. As for the project name, I don't believe the project name is here, I have another CL to add the project name to the cnrm repo.

**Comment by maqiuyujoyce** [comment]
> For point 1, does it apply to our test yamls file and doc files as well?

I think so. We in general do not want to expose any test resource information unless it's something intended to be public. E.g. a test dataset we'd be happy to share with external users.

> For point 2, currently this image is not public in the testing project, I copied this image over from gs://configconnector-operator/latest/release-bundle.tar.gz, this image is a public image used for config connector manual installation. As for the project name, I don't believe the project name is here, I have another CL to add the project name to the cnrm repo.

Ah my bad, I meant the bucket name. If we agree to share a test resource with external users, maybe it's better to use a name that doesn't contain internal code name, etc? Let's discuss this offline.

**Pull request merged**
