### PR TITLE
feat:add a label for kcc resource type

### PR DESCRIPTION
**Pull request by xiaoweim**
This PR adds a default label to KCC resource object specifying the resource type.

I would like to have a label in concord usage tables that helps me attribute the resource usage to the exact KCC resource. In order to concord to be able to get this information, we first need a label in KCC so that I can later add a label in concord with this information.

### CODE REVIEW

**Comment by yuwenma** [comment]
Do we want to add the Kind name in the KCC metadata labels as well? This is a duplicate of the ` Kind` field itself, my concern is that this could bug some users.

**Comment by justinsb** [comment]
Yeah, can you describe more what we're trying to achieve here.  AIUI the GCP resource implies the KCC resource, so I'm not sure what we're adding?  We have the `managed-by-cnrm` GCP label already if we want to know if the resource is managed by KCC

**Comment by xiaoweim** [comment]
> Yeah, can you describe more what we're trying to achieve here. AIUI the GCP resource implies the KCC resource, so I'm not sure what we're adding? We have the `managed-by-cnrm` GCP label already if we want to know if the resource is managed by KCC

Essentially I would like to have a label in concord usage tables that helps me attribute the resource usage to the exact KCC resource. In order to concord to be able to get this information, we first need a label in KCC so that I can later add a label in concord with this information.

**Comment by xiaoweim** [comment]
> Do we want to add the Kind name in the KCC metadata labels as well? This is a duplicate of the ` Kind` field itself, my concern is that this could bug some users.

So I am adding this label to pass this information to concord usage tables, not sure if KCC metadata label is needed or can do the same?

**Comment by xiaoweim** [comment]
retest/

**Comment by cheftako** [comment]
Seems like some types (Eg CloudSQLInstance) are not being labelled today.

**Comment by cheftako** [comment]
Otherwise looks good.

**Pull request closed without merging**
