### PR TITLE
feat: Add sample test for RedisCluster

### PR DESCRIPTION
**Pull request by anhdle-sso**
### Change description

Fixes #

### Tests you have done

- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [ ] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by gemmahou** [comment]
I also do no see we resolve the networkRef in the controller code: https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/cbde67b14321af37f91660a900083a66b3c5d0fe/pkg/controller/direct/redis/cluster/rediscluster_controller.go. In the fixtures test, we use external reference, so it's fine, but I noticed in the samples we reference to rediscluster-dep, we might need to resolve the networkRef, for example: https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/cbde67b14321af37f91660a900083a66b3c5d0fe/pkg/controller/direct/compute/forwardingrule/refs.go#L32

**Comment by anhdle-sso** [comment]
> Checking the log, the samples test failure error message is: https://screenshot.googleplex.com/BXMYfs38eGsT6s5.png. That might related to #2621, resolving ComputeNetwork is not required for deletion, so I had a PR to move the resolver functions out of Adapter, see #2758. I think this failure is similar?

I wrongly set the delete Protection to true which makes the delete to fail

**Comment by anhdle-sso** [comment]
> I also do no see we resolve the networkRef in the controller code: https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/cbde67b14321af37f91660a900083a66b3c5d0fe/pkg/controller/direct/redis/cluster/rediscluster_controller.go. In the fixtures test, we use external reference, so it's fine, but I noticed in the samples we reference to rediscluster-dep, we might need to resolve the networkRef, for example:
> 
> https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/cbde67b14321af37f91660a900083a66b3c5d0fe/pkg/controller/direct/compute/forwardingrule/refs.go#L32

the network ref is resolved in `VisitField` in `refs.go`

**Comment by yuwenma** [comment]
/lgtm
/approve

Thank you for the fix!

**Pull request merged**
