### PR TITLE
chore: Fix deepcopy-gen

### PR DESCRIPTION
**Pull request by gemmahou**
### Change description

We noticed our integration test failed due to a diff in the generated deepcopy file([screenshot](https://screenshot.googleplex.com/dYrkEhr7y9tzDUS.png)), however, GH presubmit passed without error. I noticed that the output of deepcopy generator in GH and Prow are different, that caused the diff in the generated deepcopy file.

Command: `go run k8s.io/code-generator/cmd/deepcopy-gen@v0.29.0 -O zz_generated.deepcopy -h ../hack/boilerplate.go.txt -i  github.com/GoogleCloudPlatform/k8s-config-connector/apis/... --trim-path-prefix github.com/GoogleCloudPlatform/k8s-config-connector/apis`

Code location: https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/dev/tasks/generate-crds#L29 

The output path was set to `github.com/GoogleCloudPlatform/k8s-config-connector/apis/...`, which is the root directory the GitHub action run against. Therefore, with the GitHub action, we were able to generate the deepcopy file and output it to the correct location. However in my local or prow job, the output dir somehow was `${LOCAL_ROOT}/github.com/GoogleCloudPlatform/k8s-config-connector/apis/...`, which caused the generated deepcopy output to go to another directory. 

In this PR I manually copy-pasted the generated deepcopy output to the correct location and resolved this, tested locally and in Github.

We can rebase PR #1880 with this one. 

I identified the issue by checking the `Code generated by deepcopy-gen. DO NOT EDIT.` comment in the file: https://screenshot.googleplex.com/B8jn9DrJchZ9YKD.png, we expected to see this after deepcopy-gen.

### Tests you have done

- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [ ] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by maqiuyujoyce** [comment]
Thank you for the fix, @gemmahou ! Do you mind adding some description about the exact issue to provide some context?

**Comment by gemmahou** [comment]
> Thank you for the fix, @gemmahou ! Do you mind adding some description about the exact issue to provide some context?

I updated the PR description, hopefully that explains the issue and my proposed fix.

**Comment by gemmahou** [comment]
/unhold

Triggered a prow presubmit job and verified that the validate-prereqs.sh passed with this code change.

**Pull request merged**
