### PR TITLE
tests:fix mockgcp for bigquery to mimic real GCP behavoir

### PR DESCRIPTION
**Pull request by xiaoweim**
- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [x] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Review by jingyih — COMMENTED** [review]
/lgtm
/approve

**Comment by jingyih** [comment]
Looks like this might affected other tests that depend on bigquerydataset. Cloud you run the whole test suite and update the affected http logs?

**Comment by xiaoweim** [comment]
> Looks like this might affected other tests that depend on bigquerydataset. Cloud you run the whole test suite and update the affected http logs?

Yes, I updated the affected test log.

**Pull request merged**
