### PR TITLE
[DNSRecordSet] implement support for internal load balancer health ch…

### PR DESCRIPTION
**Pull request by hkundag**
Geo/WRR routing policies can now reference internal load balancers that should be health checked. The internal load balancer can be specified with hardcoded constants or resource references. Some references are for the load balancer, and others are for lower level resources (e.g. `Project`, `ComputeNetwork`, `ComputeAddress`).

### Change description
Step 2 for fixing b/233267548

This PR implements support for health-checked internal load balancers as well as the primary-backup policy type.

### Tests you have done

```
go test -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete \
  -run-tests dnsrecordset -timeout 900s
```

- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [x] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by hkundag** [comment]
Currently trying to debug the primary-backup test case.

**Comment by jingyih** [comment]
Hi @hkundag, feel free to let me know when the PR is ready for review!

**Comment by hkundag** [comment]
@jingyih should be ready for review now! tests are failing though due to a mockgcp bug.

**Review by jingyih — COMMENTED** [review]
/lgtm
/approve

**Comment by hkundag** [comment]
I am not sure what's happening with the tests - in the logs for the WRR test, I can see this message:
```
{
  "severity": "info",
  "timestamp": "2024-02-11T17:19:19.529Z",
  "msg": "resource is not ready",
  "kind": "ComputeForwardingRule",
  "name": "hbrgblcbyqjgwyuqyhnaf",
  "conditions": [
    {
      "lastTransitionTime": "2024-02-11T17:19:02Z",
      "message": "reference ComputeTargetVPNGateway cnrm-test-x28596soye0ld6cr/viubdkoudhuaqwxwvxgm is not found",
      "reason": "DependencyNotFound",
      "status": "False",
      "type": "Ready"
    }
  ]
}
```

What ComputeTargetVPNGateway is it referring to? The sample files added in this PR don't make any.

**Comment by jingyih** [comment]
I tried locally and sample test is failing.

```
$ go test -v -timeout 3600s -tags=integration ./config/tests/samples/create/ -run-tests dns-routing-policy-wrr-health-checks
```

There are a lot of log entries. These maybe relevant.

```
{"severity":"info","timestamp":"2024-02-13T23:32:14.010Z","msg":"resource is not ready","kind":"DNSRecordSet","name":"znkpmhswrnutcwgatcrfpumvcqwry","conditions":[{"lastTransitionTi
me":"2024-02-13T22:57:20Z","message":"reference Project cnrm-jingyih-oncall/vwfuycagyuvfnocjkgjkdwlaup is not ready","reason":"DependencyNotReady","status":"False","type":"Ready"}]}
{"severity":"info","timestamp":"2024-02-13T23:32:15.010Z","msg":"resource is not ready","kind":"Project","name":"vwfuycagyuvfnocjkgjkdwlaup","conditions":[{"lastTransitionTime":"202
4-02-13T22:57:19Z","message":"Update call failed: error fetching live state: error converting resource config: error getting referenced resource from API server: resource reference 
is missing required 'name' field","reason":"UpdateFailed","status":"False","type":"Ready"}]}
....
    samples.go:194: timed out waiting for ready on Project with name 'vwfuycagyuvfnocjkgjkdwlaup', final status: {Generation:1 ObservedGeneration:0xc011af9690 Conditions:[{LastTrans
itionTime:2024-02-13T22:57:19Z Message:Update call failed: error fetching live state: error converting resource config: error getting referenced resource from API server: resource r
eference is missing required 'name' field Reason:UpdateFailed Status:False Type:Ready}]}
    samples.go:194: timed out waiting for ready on DNSRecordSet with name 'znkpmhswrnutcwgatcrfpumvcqwry', final status: {Generation:1 ObservedGeneration:0xc00ebb42b0 Conditions:[{LastTransitionTime:2024-02-13T22:57:20Z Message:reference Project cnrm-jingyih-oncall/vwfuycagyuvfnocjkgjkdwlaup is not ready Reason:DependencyNotReady Status:False Type:Ready}]}
```

**Pull request merged**
