### PR TITLE
Fix sample yaml

### PR DESCRIPTION
**Pull request by gemmahou**
### Change description

Fixes b/322827315

### Tests you have done

- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [ ] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by maqiuyujoyce** [comment]
lgtm/
approve/

**Comment by justinsb** [comment]
It would be good to check the schemas of all our tests ... https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/1201, I think this would have caught the logging_config error.

Now that we have pause, maybe an easy way would be to apply them all without resetting the cluster in between cc @acpana

**Comment by maqiuyujoyce** [comment]
> It would be good to check the schemas of all our tests ... https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/1201, I think this would have caught the logging_config error.

Agreed we should have test coverage for schema either via the webhook or the unit test. (Using the webhook may be more aligned with the customers' view though.)

**Pull request merged**
