### PR TITLE
Update google.golang.org/api from v0.203.0 to v0.205.0

### PR DESCRIPTION
**Pull request by haiyanmeng**
v0.205.0 includes the `configmanagement.configSync.stopSyncing` field.

### Change description

Fixes #

### Tests you have done

- [x] Run `make ready-pr` to ensure this PR is ready for review.
- [ ] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by yuwenma** [comment]
@haiyanmeng We have planned GKEHub Beta migration for the upcoming release (1.127). Do you want to include this `stopSyncing` field in this release or the one faster (next year)?

**Comment by haiyanmeng** [comment]
@yuwenma , supporting the `stopSyncing` field in KCC is not urgent, and does not need to slow down the planned KCC release. Thanks for checking.

**Comment by ziyue-101** [comment]
/lgtm
leaving the approval to Justin

**Comment by haiyanmeng** [comment]
This is no longer needed. https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3335 updated the `google.golang.org/api` version to `v0.210.0`.

**Pull request closed without merging**
