### PR TITLE
fix: Make ResourceID field "mutable"

### PR DESCRIPTION
**Pull request by jasonvigil**
In practice, due to in-controller enforcement, the only valid change is to set from empty string -> actual resource ID.

### CODE REVIEW

**Review by maqiuyujoyce — COMMENTED** [review]
Could you also remove the `Immutable.` from the field description?

**Comment by jasonvigil** [comment]
> Could you also remove the `Immutable.` from the field description?

I think it is sort of "correct" to include the immutable in the field description. The only valid change is from empty string -> actual resource id. Otherwise it is immutable.

**Comment by jasonvigil** [comment]
> > Could you also remove the `Immutable.` from the field description?
> 
> I think it is sort of "correct" to include the immutable in the field description. The only valid change is from empty string -> actual resource id. Otherwise it is immutable.

Though, maybe since it is removed from the template, we should remove from existing also. Will do.

**Comment by maqiuyujoyce** [comment]
I think "Immutable" is a very specific concept. Something like `Must be the same resource ID once successfully reconciled` may be helpful?

**Review by yuwenma — COMMENTED** [review]
/lgtm
/approve

Thanks!

**Comment by jasonvigil** [comment]
> I think "Immutable" is a very specific concept. Something like `Must be the same resource ID once successfully reconciled` may be helpful?

Agreed it will be helpful to add some comment to help users understand the validation behavior. Just added (for template and all resources)

**Pull request merged**
