### PR TITLE
tools: go work

### PR DESCRIPTION
**Pull request by acpana**
Introduces go.work. 

This is going to help w the import failures I am seeing on 2355. Cmds run:

```
# repo_root
$ go work init
$ go work use mockgcp
$ go work use .
$ go work sync
```

### CODE REVIEW

**Comment by justinsb** [comment]
Looks good, but do you mind cleaning up the reverts (`git rebase - i upstream/master`)  ?

**Comment by justinsb** [comment]
LGTM!    Any objection @yuwenma (k/k now checks in go.work, it seems to work better than replace directives) ?  I'll to you to approve

/lgtm

**Comment by yuwenma** [comment]
> LGTM! Any objection @yuwenma (k/k now checks in go.work, it seems to work better than replace directives) ? I'll to you to approve
> 
> /lgtm

I like the idea of using go work. My only concern is those version bumps on client-go, controller-runtime (and some other sig-k8s libs) makes the test core infra (which uses the mockkubeapiserver) diverge and depart from the mocked GCP.

**Comment by yuwenma** [comment]
/approve

No blocker for this change itself. I'd like to unblock the firestore

**Pull request merged**
