### PR TITLE
Stop merging sensitive fields in SQLInstance and ComputeBackendService

### PR DESCRIPTION
**Pull request by maqiuyujoyce**
### Change description

Fixes b/328854103

### Tests you have done

- [N/A] Run `make ready-pr` to ensure this PR is ready for review.
- [X] Perform necessary E2E testing for changed resources.

Test details can be found at #1343 .

### CODE REVIEW

**Comment by justinsb** [comment]
I have questions on the buganizer bug.  I think we should bring those conversations here in future.

**Comment by justinsb** [comment]
This seems like a reasonable workaround.  Should we / can we do this for ComputeBackendService also?  That's my only blocker

/approve
/lgtm

/hold for ComputeBackendService question

**Comment by maqiuyujoyce** [comment]
> This seems like a reasonable workaround. Should we / can we do this for ComputeBackendService also? That's my only blocker
> 
> /approve /lgtm
> 
> /hold for ComputeBackendService question

Yep, that's doable. I'll update the PR.

**Comment by justinsb** [comment]
Thanks @maqiuyujoyce 

/approve
/lgtm

**Comment by maqiuyujoyce** [comment]
@justinsb could you take another look when you get a chance?

**Comment by justinsb** [comment]
I already approved, this just has a hold on it.

/hold cancel

(Waiting on tests)

**Pull request merged**
