### PR TITLE
(Part 4)Fix diffs in compute forwarding rule: normalize `IPAddress` in golden logs

### PR DESCRIPTION
**Pull request by gemmahou**
### Change description

based on #2724, check the last commit in this PR

When executing the tests against realGCP, the ip address will be generated by GCP if not provided. Normalize the ip address to be `8.8.8.8` as the fake ip we wrote in ComputeAddress mock server, to avoid diffs between mock and real.

### Tests you have done

- [ ] Run `make ready-pr` to ensure this PR is ready for review.
- [ ] Perform necessary E2E testing for changed resources.

### CODE REVIEW

**Comment by justinsb** [comment]
Reviewed last commit, lgtm

**Review by yuwenma — COMMENTED** [review]
The last commit looks good. Pending approval for the discussions in the diff-base PRs

**Comment by yuwenma** [comment]
The presubmit failure looks weird. you may want to rebase from head.

**Pull request merged**
