### PR TITLE
tools: auto insert the generated field and messaged from a new proto field

### PR DESCRIPTION
**Pull request by jingyih**
The insertion is mechanical, based on go file parsing.

This PR is rebased on #2425, which is AI-based inseration.

Future work:
 - Update mappers (should be able to update mappers by rerunning the mapper generator)
 - Update tests and docs, etc

### CODE REVIEW

**Comment by jingyih** [comment]
How do we fix merge conflict on go.work? @yuwenma 

```
Conflicting files

dev/tools/controllerbuilder/go.mod
dev/tools/controllerbuilder/go.sum
go.work.sum
```

**Review by jasonvigil — COMMENTED** [review]
This is cool 👍

**Comment by jingyih** [comment]
Rebased

**Pull request merged**
