### PR TITLE
github CI: upload artifacts directory

### PR DESCRIPTION
**Pull request by justinsb**
This lets us see richer and more structured output than we get with
just the logfile.

### CODE REVIEW

**Review by diviner524 — APPROVED** [review]
I don't see anything gets uploaded, I assume it is expected as we haven't enabled artifacts for mock tests?

https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/6338592433/job/17216027901#step:6:10

**Comment by jingyih** [comment]
On a side note, how do we apply "approved" and "lgtm" labels to make tide happy?

**Pull request merged**
